# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dataset_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(default=9),
        ),
    ]
